name: Static Site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check HTML syntax
        uses: Cyb3r-Jak3/htmlhint-action@v1
        with:
          config: .htmlhintrc # optional, or remove this line to use defaults

      - name: Check for broken links in index.html
        run: |
          sudo apt-get update
          sudo apt-get install -y linkchecker
          linkchecker index.html || echo "Broken links detected"
